### ISSUE TITLE
Function tooltips outside of viewable area

### ISSUE THREAD

**Issue by lyzidiamond** [tmcw/rpl-www#14]
In the first couple lines of the rpl, the function tooltips are outside the viewable space:

![screen shot 2015-01-21 at 10 05 06 am 2](https://cloud.githubusercontent.com/assets/2523165/5841905/6066d66c-a155-11e4-94d3-c79b6c7fca49.png)

**Comment by tmcw** [comment]
Yep, folding into #12 - I'm kinda bummed about the state of tooltip libraries and haven't found much that handles all the cases well enough. Potentially these should be things on the right side, rather than over the hovered point.
